### ISSUE TITLE
Parsing error loading recipe notenoughwands:acceleration_wand

### ISSUE THREAD

**Issue by Napkin** [romelo333/notenoughwands#102]
On a dedicated server loading notenoughwands-1.14-1.7.5.beta.jar, this error shows up on start-up:

`[20:32:43] [Server thread/ERROR]: Parsing error loading recipe notenoughwands:acceleration_wand
com.google.gson.JsonSyntaxException: Unknown item 'minecraft:dye'
        at net.minecraft.class_1856.method_17873(class_1856.java:162) ~[intermediary-server.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_171]
        at net.minecraft.class_1856.method_8107(class_1856.java:162) ~[intermediary-server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:139) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_14491(class_1863.java:61) ~[intermediary-server.jar:?]
        at net.minecraft.class_4013.method_18235(class_4013.java:12) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) ~[?:1.8.0_171]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_171]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_171]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:135) [intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:114) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:702) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:696) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:123) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1466) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:450) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:366) [intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:218) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:605) [intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]`
Thanks for this mod!

**Comment by SDUBZ** [comment]
@McJty Would be nice to get these issues fixed

**Comment by McJty** [comment]
Unfortunatelly I do not have the time right now to maintain the Fabric versions of my mods. There is too much on my plate so for now the fabric versions are considered obsolete until someone (or me when I finally get around to it) update them
