### ISSUE TITLE
Crash on 1.11.2

### ISSUE THREAD

**Issue by redlap2** [romelo333/notenoughwands#56]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  llibrary (llibrary-1.7.4-1.11.2.jar)
  LoadingPlugin (Quark-r1.2-90.jar)
  MalisisSwitchesPlugin (malisisswitches-1.11.2-4.1.0.jar)
  MoreCommandsLoadingPlugin (MoreCommands-1.11.2-5.0.jar)
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.4.jar)
  LoadingPlugin (RandomThings-MC1.11.2-3.8.1.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.3.6.1.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 4/25/17 2:42 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.block.model.FaceBakery.func_178404_a(FaceBakery.java:202)
	at net.minecraft.client.renderer.block.model.FaceBakery.fillVertexData(FaceBakery.java:189)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeQuadVertexData(FaceBakery.java:112)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeBakedQuad(FaceBakery.java:76)
	at net.minecraft.client.renderer.block.model.FaceBakery.func_178414_a(FaceBakery.java:58)
	at BlockModelUtils.makeBakedQuad(BlockModelUtils.java:84)
	at BlockModelUtils.makeModelCube(BlockModelUtils.java:61)
	at BetterGrass.update(BetterGrass.java:73)
	at TextureUtils.resourcesReloaded(TextureUtils.java:295)
	at TextureUtils$1.func_110549_a(TextureUtils.java:338)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at TextureUtils.registerResourceListener(TextureUtils.java:342)
	at net.minecraft.client.renderer.EntityRenderer.frameInit(EntityRenderer.java:2751)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1282)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 4.10.0-20-generic
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 115070344 bytes (109 MB) / 775831552 bytes (739 MB) up to 6388776960 bytes (6092 MB)
	JVM Flags: 5 total; -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 Optifine OptiFine_1.11.2_HD_U_B7 74 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	U	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	U	backpacks16840{3.1.9} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.9.jar) 
	U	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	U	abyssalcraft{1.9.4-pre-2} [AbyssalCraft] (AbyssalCraft-1.11.2-1.9.4-pre-2.jar) 
	U	actuallyadditions{1.11.2-r106} [Actually Additions] (ActuallyAdditions-1.11.2-r106.jar) 
	U	additionalbanners{1.4.0.25} [Additional Banners] (AdditionalBanners-1.11.2-1.4.0.25.jar) 
	U	animania{1.0.4.6} [Animania] (animania-1.11.2-1.0.4.6.jar) 
	U	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	U	battleaxes{1.0.0} [Fancy Battleaxes] (Battleaxes[1.11.2]-1.1.1.jar) 
	U	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	U	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.1.239+9162f74.jar) 
	U	betterfoliage{2.1.4} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.4.jar) 
	U	biomesoplenty{6.0.2.2171} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.2.2171-universal.jar) 
	U	birdsnests{1.5.1} [Bird's Nests] (BirdsNests1.11.2-1.5.1.jar) 
	U	blockarmor{2.4.3} [Block Armor] (BlockArmor-1.11.2-2.4.3.jar) 
	U	blocklings{4.1.4} [WillR27's Blocklings] (Blocklings 4.1.4 - 1.11.2.jar) 
	U	botania{r1.9-343} [Botania] (Botania r1.9-343.jar) 
	U	buildcraftfactory{7.99.0} [BC Factory] (buildcraft-7.99.0.jar) 
	U	buildcrafttransport{7.99.0} [BC Transport] (buildcraft-7.99.0.jar) 
	U	buildcraftlib{7.99.0} [BuildCraft Lib] (buildcraft-7.99.0.jar) 
	U	buildcraftbuilders{7.99.0} [BC Builders] (buildcraft-7.99.0.jar) 
	U	buildcraftcore{7.99.0} [BuildCraft] (buildcraft-7.99.0.jar) 
	U	buildcraftenergy{7.99.0} [BC Energy] (buildcraft-7.99.0.jar) 
	U	buildcraftrobotics{7.99.0} [BC Robotics] (buildcraft-7.99.0.jar) 
	U	buildcraftsilicon{7.99.0} [BC Silicon] (buildcraft-7.99.0.jar) 
	U	ceanimals{1.3.0} [Crop-Eating Animals] (ceanimals-1.11.2-1.3.0.jar) 
	U	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	U	chameleoncreepers{1.4.1} [Chameleon Creepers] (chameleoncreepers-1.4.2-1.11.2.jar) 
	U	chisel{MC1.11.2-0.0.10.14} [Chisel] (Chisel-MC1.11.2-0.0.10.14.jar) 
	U	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	U	craftsaddlesmod{1.0} [Craft Saddles and Horse Armor] (craftsaddlesmod-1.0.jar) 
	U	crystalcaves{1.0} [Crystal Caves] (CrystalCaves-1.0.jar) 
	U	custombackgrounds{1.0} [Custom Backgrounds] (CustomBackgrounds-MC1.11-1.1.jar) 
	U	custommainmenu{2.0.5} [Custom Main Menu] (CustomMainMenu-MC1.11.2-2.0.5.jar) 
	U	customnpcs{1.11.2} [CustomNPCs] (CustomNPCs_1.11.2_beta(17mar17).jar) 
	U	cyclicmagic{1.3.0} [Cyclic] (Cyclic-1.11.2-1.3.0.jar) 
	U	props{2.4.1} [Decocraft] (Decocraft-2.4.1_1.11.2.jar) 
	U	doggytalents{v1.12.1c} [Doggy Talents] (DoggyTalents-1.11.2-v1.12.1c-universal.jar) 
	U	hobomod{1.0} [Hobo's Dyeable Chickens] (dyeablechickens-1.0.jar) 
	U	dsurround{3.3.6.1} [Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.3.6.1.jar) 
	U	epicsiegemod{12.0.157} [Epic Siege Mod] (EpicSiegeMod-12.0.157.jar) 
	U	fairylights{2.1.0} [Fairy Lights] (fairylights-2.1.0-1.11.2.jar) 
	U	fbp{2.2} [Fancy Block Particles] (FancyBlockParticles-1.11.2-2.2.jar) 
	U	flatcoloredblocks{mc1.11-5.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.11-5.1.jar) 
	U	infernalmobs{1.7.2} [Infernal Mobs] (InfernalMobs-1.11.2.jar) 
	U	jei{4.3.3.266} [Just Enough Items] (jei_1.11.2-4.3.3.266.jar) 
	U	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	U	buildingblocks{1.0} [Just Build It] (JustBuildIt MC1.11.2 v1.0.jar) 
	U	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.2.jar) 
	U	malisisblocks{1.11.2-5.1.0} [Malisis Blocks] (malisisblocks-1.11.2-5.1.0.jar) 
	U	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
	U	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
	U	malisisswitches{1.11.2-4.1.0} [Malisis Switches] (malisisswitches-1.11.2-4.1.0.jar) 
	U	crystalic_void{2.4.7} [Meldexun's Crystalic Void] (Meldexun'sCrystalicVoid-1.11.2-2.4.7.jar) 
	U	mrnobody_morecommands{5.0} [MoreCommands] (MoreCommands-1.11.2-5.0.jar) 
	U	notenoughwands{1.5.4} [Not Enough Wands] (notenoughwands-1.1x-1.5.4.jar) 
	U	notes{1.1.0} [Notes] (Notes-1.11.2-1.1.0.jar) 
	U	overlord{2.3.3} [Overlord] (Overlord-1.11.2-2.3.3.jar) 
	U	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2g.jar) 
	U	pattysmorestuff{stable-1.0.4} [Pattys More Stuff] (PattysMoreStuff-stable-1.0.4.jar) 
	U	platforms{1.3.4} [Platforms] (platforms-1.11.0-1.3.4.jar) 
	U	quark{r1.2-90} [Quark] (Quark-r1.2-90.jar) 
	U	randomthings{3.8.1} [Random Things] (RandomThings-MC1.11.2-3.8.1.jar) 
	U	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	U	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	U	roughmobs{1.0} [Rough Mobs] (roughMobs1.0.9-1.11.2.jar) 
	U	shetiphiancore{3.4.4} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.4.jar) 
	U	buildhelper{0.4.2} [Torojima's Build Helper] (torojimaBuildHelper-0.4.2.jar) 
	U	undergroundbiomes{1.0.v.18} [Underground Biomes] (UndergroundBiomesConstructs-1.11-1.0.v.18.1.jar) 
	U	thejungle{1.0.194} [Welcome to the Jungle] (Welcome to the Jungle-1.04.1112.jar) 
	U	worldedit{6.1.6} [WorldEdit] (worldedit-forge-mc1.11-6.1.6-dist.jar) 
	Loaded coremods (and transformers): 
ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  team.chisel.common.asm.ChiselTransformer
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
llibrary (llibrary-1.7.4-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (Quark-r1.2-90.jar)
  vazkii.quark.base.asm.ClassTransformer
MalisisSwitchesPlugin (malisisswitches-1.11.2-4.1.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
MoreCommandsLoadingPlugin (MoreCommands-1.11.2-5.0.jar)
  com.mrnobody.morecommands.asm.transform.TransformBlockRailBase
  com.mrnobody.morecommands.asm.transform.TransformForgeHooks
  com.mrnobody.morecommands.asm.transform.TransformItemStack
  com.mrnobody.morecommands.asm.transform.TransformStyle
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.4.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
LoadingPlugin (RandomThings-MC1.11.2-3.8.1.jar)
  lumien.randomthings.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  shetiphian.core.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.3.6.1.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
  brad16840.common.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 375.39' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2282
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 375.39, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3 CPU 530 @ 2.93GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Continuum-§91.3-§f§2Low§f-§4Ultra§f.zip
	OpenGlVersion: 4.5.0 NVIDIA 375.39
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by McJty** [comment]
Can you also tell me what exactly you were doing? It is hard to judge from this

**Comment by redlap2** [comment]
Nothing, I was adding mods for my kid. I usually put one, execute Minecraft and if it works, I put the next. When I put this one, Minecraft crashed while loading. I didn't get to the menu.

**Comment by redlap2** [comment]
I tried it again without any other mods.

Only this 2:

notenoughwands-1.1x-1.5.4.jar
compatlayer-1.11.2-0.2.5.jar

and I get this:

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 4/25/17 10:53 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Wands (notenoughwands)
Caused by: java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyContainerItem
	at romelo333.notenoughwands.ModItems.init(ModItems.java:27)
	at romelo333.notenoughwands.proxy.CommonProxy.preInit(CommonProxy.java:20)
	at romelo333.notenoughwands.proxy.ClientProxy.preInit(ClientProxy.java:25)
	at romelo333.notenoughwands.NotEnoughWands.preInit(NotEnoughWands.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:275)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyContainerItem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 43 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 4.10.0-20-generic
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 188899144 bytes (180 MB) / 572035072 bytes (545 MB) up to 6388776960 bytes (6092 MB)
	JVM Flags: 5 total; -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	UCH	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCE	notenoughwands{1.5.4} [Not Enough Wands] (notenoughwands-1.1x-1.5.4.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 375.39' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'

**Comment by McJty** [comment]
Ok, that last one is known. You need some kind of RF mod like McJtyLib

But that first crash does not seem related to Not Enough Wands at all

**Comment by redlap2** [comment]
OK, thanks. It's working now.

I got it from here:

https://minecraft.curseforge.com/projects/not-enough-wands

and I don't see any reference to McJtyLib in the description. I see it now
on the posts.

Thanks for taking the time to answer. :)
